MULTIPLICATION_RATIO = 4
DPI = 96
LAYER_HEIGHT = 0.3
INPUT_FILE = "./input/Carrier-B_Cu.svg"
TMP_IMG = "./tmp/tmp.png"
TMP_BW_IMG = "./tmp/tmp_bw.png"
OUTPUT_FILE ="output.png"
RELATIVE = True
NOZZLE_SIZE = 0.3